name: CI/CD for Node.js App with Docker

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/x-factor-be:${{ github.sha }} .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/x-factor-be:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt sshpass để sử dụng SSH với mật khẩu
      - name: Install sshpass
        run: sudo apt-get install sshpass

      # Kết nối tới VPS và triển khai ứng dụng
      - name: Deploy to VPS
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_IP }} "bash -s" << 'EOF'
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker pull $DOCKER_USERNAME/my-new-nodejs-app:latest
            docker stop nodejs-app || true
            docker rm nodejs-app || true
            docker run --env-file .env -d --name nodejs-app -p 80:4000 $DOCKER_USERNAME/my-new-nodejs-app:latest
          EOF
