name: Send Webhook Notification

on:
  workflow_run:
    workflows: ['Build and Deploy']
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook notification
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          curl -X POST https://axolo-webhook-url.com -H "Content-Type: application/json" \
          -d '{"text": "Build success for commit ${{ github.sha }}", "channel": "slack-channel", "email": "do.quang039@gmail.com"}'
